### ISSUE TITLE
[bug] comments not loading

### ISSUE THREAD

**Issue by LES-11** [Scratch-Client-4/itchy-ionic#61] opened 2022-04-05 04:23 UTC
Profile comments won't load.
Also some things just take a while to load but I think that's just optimization and might also be a fault on my end (slow wifi, older device, etc.)

![Screenshot_20220403-203035](https://user-images.githubusercontent.com/75516401/161678259-ce252853-65bf-448c-845b-cfdb2ce61e52.jpg)

**Comment by locness3** [comment] 2022-04-05 10:20
I'll try to reproduce later.

**Comment by micahlt** [comment] 2022-04-16 23:43
Hmm, I'm not able to reproduce this.  Can you provide details about your device?  What device are you using?

**Comment by micahlt** [comment] 2022-04-16 23:49
Oh, also this is a duplicate of #55, so any further info should be relegated to that issue.

**Closed by micahlt** 2022-04-16 23:49 UTC
Labels: invalid, question, platform:android
